networks:
  thesis_net:
    external: true
    
services:
 xdebug2:
   image: vulhub/php:7.1-xdebug
   ports:
    - "9999:80"
   volumes:
    - ./index.php:/var/www/html/index.php
    - ./init.sh:/init.sh
   entrypoint: ["sh", "/init.sh"]
   cap_add:
    - "NET_ADMIN"
   networks:
    thesis_net:
        ipv4_address: 172.20.0.7
