version: '2.3'
networks:
  thesis_net:
    external: true
services:
  redis:
    image: redis:5.0.9-alpine
    networks:
      thesis_net:
        ipv4_address: 172.20.0.22
  postgresql:
    image: postgres:12-alpine
    environment:
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=gitlabhq_production
    - DB_EXTENSION=pg_trgm,btree_gist
    networks:
      thesis_net:
        ipv4_address: 172.20.0.21
  gitlab:
    image: vulhub/gitlab:13.10.1
    depends_on:
    - redis
    - postgresql
    environment:
    - DEBUG=false
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false
    - GITLAB_HOST=localhost
    - GITLAB_PORT=8080
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=long-long-long-long-long-long-secret-key-is-here1
    - GITLAB_SECRETS_SECRET_KEY_BASE=long-long-long-long-long-long-secret-key-is-here2
    - GITLAB_SECRETS_OTP_KEY_BASE=long-long-long-long-long-long-secret-key-is-her3
    - TZ=Asia/Kolkata
    - GITLAB_TIMEZONE=Kolkata
    - GITLAB_ROOT_PASSWORD=vulhub123456
    ports:
      - "8080:8080"
    volumes:
      - ./init_gitlab.sh:/init_gitlab.sh
    entrypoint: ["sh", "/init_gitlab.sh"]
    cap_add:
      - NET_ADMIN
    networks:
      thesis_net:
        ipv4_address: 172.20.0.20
  gitlab-proxy:
    image: nginx:alpine
    container_name: cve-2021-22205-gitlab-1-proxy
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./init_proxy.sh:/init_proxy.sh
    entrypoint: ["sh", "/init_proxy.sh"]
    cap_add:
      - NET_ADMIN
    depends_on:
      - gitlab
    networks:
      thesis_net:
        ipv4_address: 172.20.0.10
